paths:
  /api/feedback:
    post:
      summary: Submit feedback
      tags:
        - Feedback
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeedbackRequest"
      responses:
        "201":
          description: Feedback submitted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        "500":
          description: Server error

    get:
      summary: List all feedbacks (admin)
      tags:
        - Feedback
      responses:
        "200":
          description: List of feedbacks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Feedback"

  /api/feedback/{id}:
    get:
      summary: Get specific feedback (including reply)
      tags:
        - Feedback
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Feedback with reply
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        "404":
          description: Feedback not found
        "500":
          description: Server error

  /api/feedback/{id}/reply:
    put:
      summary: Reply to feedback and send SMS
      tags:
        - Feedback
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - reply
              properties:
                reply:
                  type: string
      responses:
        "200":
          description: Feedback replied successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feedback"
        "500":
          description: Server error

components:
  schemas:
    FeedbackRequest:
      type: object
      required:
        - phone
        - message
        - stars
        - bill_id
      properties:
        phone:
          type: string
        message:
          type: string
        stars:
          type: integer
          minimum: 1
          maximum: 5
        bill_id:
          type: string

    Feedback:
      type: object
      properties:
        _id:
          type: string
        phone:
          type: string
        message:
          type: string
        reply:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
